// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3A1DVLraguE3yepQkdj0cehXqKJNBD4',
    appId: '1:843099114792:android:78d05478a749bb6c6c541d',
    messagingSenderId: '843099114792',
    projectId: 'flutter-chat-app-8a0b9',
    databaseURL: 'https://flutter-chat-app-8a0b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-8a0b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbAWpvL0yK2jmxlTezNvf10bnQmhOdVQ',
    appId: '1:843099114792:ios:4401e9084018c7696c541d',
    messagingSenderId: '843099114792',
    projectId: 'flutter-chat-app-8a0b9',
    databaseURL: 'https://flutter-chat-app-8a0b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-8a0b9.appspot.com',
    iosClientId: '843099114792-3n00brq87esaqam2g7ms8u72t5fu4hlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
